version: '3.8'
services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '11434:11434'
    volumes:
      - ~/.ollama:/root/.ollama

  openweb-ui:
    container_name: openweb-ui
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - internal
    depends_on:
      - ollama
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=$OLLAMA_BASE_URL
      - WEBUI_SECRET_KEY=
    restart: unless-stopped
    ports:
      - '8081:8080'
    volumes:
      - open_webui_data:/app/backend/data

  # chatgpt:
  #   container_name: chatgpt
  #   image: pawanosman/chatgpt:latest
  #   networks:
  #     - internal
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   ports:
  #     - '3040:3040'

  unstructured-api:
    container_name: unstructured-api
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '8082:8000'

  chroma:
    container_name: chroma
    image: ghcr.io/chroma-core/chroma:latest
    networks:
      - internal
    restart: unless-stopped
    ports:
      - '8084:8000'
    volumes:
      - chroma_data:/chroma/chroma/

  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - internal
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  langchain-playground:
    container_name: langchain-playground
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '8080:8080'

networks:
  internal:
    driver: bridge

volumes:
  open_webui_data:
  redis_data:
  chroma_data:
